name: api_widget
description: A powerful and flexible Flutter widget for handling API requests with built-in loading states, error handling, and retry mechanisms.
version: 1.0.2
homepage: https://github.com/Digvijaysinh2204/Api-Widget
repository: https://github.com/Digvijaysinh2204/Api-Widget
issue_tracker: https://github.com/Digvijaysinh2204/Api-Widget/issues
documentation: https://github.com/Digvijaysinh2204/Api-Widget/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  http: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15


